name: CI

on: pull_request

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1 
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install    
        
      - name: Linters and test
        run: npm run lint && npm run test:ci
